@extends('layouts.layout')

@section('content')

    <body>

        <div id="main" class="row">

            @yield('content')

        </div>


        <div class="form">
            <form>

                //the type of chart
                <div class="form-group">
                    <label for="charts">Example select</label>
                    <select class="form-control" id="chart">
                        <option>Pie Chart</option>
                        <option>Line Chart</option>
                    </select>
                </div>


                //the number of data points
                <div class="form-group">
                    <label for="datasets">Example multiple select</label>
                    <select multiple class="form-control" id="dataset">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>


                {{--  <div id="dataSets" class="form-group">
                    <label for="exampleFormControlTextarea1">{{ $dataset }}</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>


                <div id="myHTMLWrapper">

                </div>  --}}

                <script>
                  var wrapper = document.getElementById("dataSets");

                  var myHTML = ''

                  for (var i = 0; i < document.getElementById("dataset").value; i++) {
                    myHTML += '<div id="dataSets" class="form-group"><label for="exampleFormControlTextarea1">' + 'Data Value '  +  i + ' </label><textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea></div>';;
                  }
                  wrapper.innerHTML = myHTML
                </script>




                <input type="text" name="chance" value=""
                    onkeyup="document.querySelector('input[name=payout]').value=this.value?1/this.value*98:''">



                <div class="form-group">
                    <label for="exampleFormControlInput1">Email address</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Example select</label>
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect2">Example multiple select</label>
                    <select multiple class="form-control" id="exampleFormControlSelect2">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Example textarea</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
            </form>
        </div>


    </body>
    <style>
        .form {
            margin: auto;
            margin-top: 50px;
            width: 50%;
        }

    </style>
@endsection

{{-- const config = {
    type: 'pie',
    data:{
        labels: [
          'Red',
          'Blue',
          'Yellow'
        ],
        datasets: [{
          label: 'My First Dataset',
          data: [300, 50, 100],
          backgroundColor: [
            'rgb(255, 99, 132)',
            'rgb(54, 162, 235)',
            'rgb(255, 205, 86)'
          ],
          hoverOffset: 4
        }]
      };,
  }; --}}


{{-- text
  list of textfield
  text
  percents
  colours(this should be autogenerated)
  hoverover set a
uto to 4? --}}
